import type { Metadata } from "next";
import { DM_Mono as FontSans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  weight: ["300", "400", "500"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Joyce Shi",
  description: "Generated by create next app",
  icons: {
    icon: "/icon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "px-4 pt-4 sm:px-[10px] sm:pt-[10px]",
          fontSans.className
        )}
      >
        <Navbar />
        {children}
        <br className="mb-[10px]" />
        <footer className="fixed w-full py-[8px] bottom-0 bg-white text-sm">
          © Joyce Shi 2016-2024.
        </footer>
      </body>
    </html>
  );
}
